apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dp1
spec:  
  replicas: 2
  selector:
    matchLabels:      
      run: nginx
  template:
    metadata:
      name: nginx-pod
      labels:
        run: nginx
    spec:
     containers:
     - name: nginx-con
       image: nginx:1.7.9
       ports:
       - containerPort: 80

