apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    env:
    - name: CHANNELNAME
      valueFrom:
        configMapKeyRef:
          name: demo-cm
          key: channel.name

    - name: CHANNELOWNER
      valueFrom:
        configMapRef:
          name: demo-cm
          key: channel.owner
