apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-replica
spec:
  replicas: 2
  selector:
    run: nginx
  template:
    metadata:
      name: nginx-pod
      labels:
        run: nginx
    spec:
     containers:
     - name: nginx-con
       image: nginx
       ports:
       - containerPort: 80

