apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
spec:
  replicas: 2
  selector:
    matchLabels:      
      run: nginx
  template:
    metadata:
      name: nginx-pod
      labels:
        run: nginx
    spec:
     containers:
     - name: nginx-con
       image: nginx
       ports:
       - containerPort: 80

